name = "adikal-astro-site"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]
main = "src/worker.ts"

[assets]
directory = "./dist"
binding = "ASSETS"

[build]
command = "npm run build"
